import turtle
turtle.shape("turtle")
turtle.speed(1)

turtle.color('red')
turtle.fillcolor('yellow')

turtle.forward(50)
turtle.right(120)
turtle.forward(15)
turtle.penup()
turtle.forward(5)
turtle.pendown()
turtle.forward(15)
turtle.penup()
turtle.forward(5)
turtle.pendown()
turtle.forward(15)
turtle.penup()
turtle.forward(5)
turtle.pendown()
turtle.forward(15)
turtle.penup()
turtle.forward(5)
turtle.pendown()
turtle.forward(15)
turtle.penup()
turtle.forward(5)
turtle.pendown()
turtle.right(150)
turtle.forward(15)
turtle.penup()
turtle.forward(5)
turtle.pendown()
turtle.forward(15)
turtle.penup()
turtle.forward(5)
turtle.pendown()
turtle.forward(15)
turtle.penup()
turtle.forward(5)
turtle.pendown()
turtle.forward(15)
turtle.penup()
turtle.forward(5)
turtle.pendown()

